//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleBilling_v02_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agreement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Agreement()
        {
            this.ZoneRecords = new HashSet<ZoneRecords>();
        }
    
        public int Id { get; set; }
        public string Customer_cvr { get; set; }
        public string Customer_name { get; set; }
        public string Subscriber_range_start { get; set; }
        public string Subscriber_range_end { get; set; }
        public string Description { get; set; }
        public bool Status { get; set; }
        public System.DateTime Date { get; set; }
        public int UserId { get; set; }
        public int CSVFileId { get; set; }
    
        public virtual User User { get; set; }
        public virtual CSVFile CSVFile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZoneRecords> ZoneRecords { get; set; }
    }
}
