//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleBilling_v02_.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBModelsContainer : DbContext
    {
        public DBModelsContainer()
            : base("name=DBModelsContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agreement> AgreementSet { get; set; }
        public virtual DbSet<User> UserSet { get; set; }
        public virtual DbSet<Supplier> SupplierSet { get; set; }
        public virtual DbSet<CSVFile> CSVFileSet { get; set; }
        public virtual DbSet<ZoneRecords> ZoneRecordsSet { get; set; }
        public virtual DbSet<InvoiceRecords> InvoiceRecordsSet { get; set; }
        public virtual DbSet<Type> TypeSet { get; set; }
    }
}
