//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleBilling_v02_.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class InvoiceRecords
    {
        public int Id { get; set; }
        public string Id_call { get; set; }
        public System.DateTime Time { get; set; }
        public string Subscriber { get; set; }
        public string Aprefix { get; set; }
        public string Destination { get; set; }
        public string Invoice_group { get; set; }
        public string Prefix { get; set; }
        public string Pbx { get; set; }
        public string Direction { get; set; }
        public string Volume_time_secs { get; set; }
        public string Price { get; set; }
        public string Free { get; set; }
        public string Forward { get; set; }
        public string Servingnetwork { get; set; }
        public string Reason { get; set; }
        public string Billed { get; set; }
        public string ZoneName { get; set; }
        public string RPBilled { get; set; }
        public int CSVFileId { get; set; }
    
        public virtual CSVFile CSVFile { get; set; }

        [NotMapped]
        public string Subscriber_cvr { get; set; }
        
    }
}
